name       : haskell-cereal
version    : 0.5.5.0
release    : 2
source     :
    - https://hackage.haskell.org/package/cereal-0.5.5.0/cereal-0.5.5.0.tar.gz : 0b97320ffbfa6df2e5679022215dbd0fe6e3b5ae8428c2ff4310d9e1acf16822
license    : BSD-3-Clause
component  : programming.haskell
summary    : A binary serialization library, similar to binary, that introduces an isolate primitive for parser isolation, and labeled blocks for better error messages.
description: "A binary serialization library, similar to binary, that introduces an isolate primitive for parser isolation, and labeled blocks for better error messages. \n"
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
