name       : haskell-cereal
version    : 0.5.4.0
release    : 1
source     :
    - http://hackage.haskell.org/package/cereal-0.5.4.0/cereal-0.5.4.0.tar.gz : daca6c5aeff21ca233bebe006c158b0e4421b239c722768b568fca9b32cafee7
license    : BSD-3-Clause
component  : programming.haskell
summary    : A binary serialization library, similar to binary, that introduces an isolate primitive for parser isolation, and labeled blocks for better error messages. 
description: |
    A binary serialization library, similar to binary, that introduces an isolate primitive for parser isolation, and labeled blocks for better error messages. 
builddeps  :
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register