name       : haskell-cereal
version    : 0.5.8.1
release    : 3
source     :
    - https://hackage.haskell.org/package/cereal-0.5.8.1/cereal-0.5.8.1.tar.gz : 2d9e88ac934b9ebc058097c72011ff59f3f146176310e1c957a0e4cf63681bd7
license    : BSD-3-Clause
component  : programming.haskell
summary    : A binary serialization library, similar to binary, that introduces an isolate primitive for parser isolation, and labeled blocks for better error messages.
description: |
    A binary serialization library, similar to binary, that introduces an isolate primitive for parser isolation, and labeled blocks for better error messages.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
